include: package:lints/recommended.yaml

linter:
  rules:
    - directives_ordering
    - library_annotations
    - prefer_relative_imports
    - sort_pub_dependencies
    - always_declare_return_types
    - comment_references
    - conditional_uri_does_not_exist
    - type_annotate_public_apis
