name: pkgs
description: An experimental tool to manage mono-repos.
version: 0.1.0-dev
repository: https://github.com/devoncarew/pkgs

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
