name: pkgs
description: A sample command-line application.
version: 0.1.0-dev
repository: https://github.com/devoncarew/pkgs

environment:
  sdk: ^2.19.0

dependencies:
  path: ^1.8.0
  yaml: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
