name: package:pkgs
permissions: read-all

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        sdk: [2.18.0, stable, dev] # {pkgs.versions}
        type: [analyze]
        include:
          - sdk: stable
            type: test
        exclude:
          - sdk: stable
            type: analyze
    # name: package:pkgs ${{ matrix.sdk }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: ${{matrix.sdk}}

      - run: dart pub get

      - run: dart analyze --fatal-infos

      - run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.type == 'test' }}

      - run: dart test
        if: ${{ matrix.type == 'test' }}
